/* =========================================================
   Ciclo Bot — base de conhecimento (regras, sem IA)

   Fontes usadas nas respostas:
   - Ecopontos (PEVs) de Guarulhos, o que recebem e o que NÃO recebem:
     Agência Mural, 10/10/2025 (https://agenciamural.org.br/confira-onde-estao-os-ecopontos-de-guarulhos/)
   - Cores da coleta seletiva: Resolução CONAMA nº 275/2001, anexo (PDF oficial do CONAMA)
   - Logística reversa (lojas e fabricantes devem receber de volta): Lei 12.305/2010, art. 33
     (pilhas e baterias, pneus, óleos lubrificantes, lâmpadas fluorescentes, eletroeletrônicos)

   Campos de cada item:
   id, nome, palavras (sinônimos e variações), resposta (frase curta),
   ondeDescartar, lixeira (cor CONAMA 275/2001 ou null), dicaReducao,
   confianca: "confirmado"                  → a fonte confirma o destino (matéria lista como aceito no Ecoponto)
              "confirme com a prefeitura"   → não há regra confirmada: o bot NÃO afirma o destino
   tipoPonto: "pev" | "doacao" | "varejo" | "nenhum"  (liga com shared/pontos.js)
   ========================================================= */
(function (raiz) {
  "use strict";

  var CONFIRMADO = "confirmado";
  var CONFIRME = "confirme com a prefeitura";
  var PEV_SIM = "Pode levar a um Ecoponto (PEV) de Guarulhos: a matéria da Agência Mural lista esse material entre os aceitos. Para grandes quantidades, veja os limites no site da Prefeitura.";
  var REVERSA = "Pela Lei 12.305/2010 (art. 33), quem fabrica e vende esse produto é obrigado a ter logística reversa, ou seja, receber de volta. Pergunte nas lojas que vendem o produto e confirme com a Prefeitura de Guarulhos.";

  var LIXEIRAS = {
    azul: "azul (papel e papelão)",
    vermelho: "vermelha (plástico)",
    verde: "verde (vidro)",
    amarelo: "amarela (metal)",
    preto: "preta (madeira)",
    laranja: "laranja (resíduos perigosos)",
    branco: "branca (resíduos de serviços de saúde)",
    roxo: "roxa (resíduos radioativos)",
    marrom: "marrom (resíduos orgânicos)",
    cinza: "cinza (não reciclável, misturado ou contaminado)"
  };

  var ITENS = [
    /* ---------- Eletrônicos ---------- */
    { id: "celular", nome: "Celular", palavras: ["celular", "smartphone", "telefone", "iphone", "aparelho celular", "tablet"],
      resposta: "Celular é lixo eletrônico: nunca no lixo comum.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita celular. " + REVERSA,
      lixeira: null, dicaReducao: "Se ainda funciona, doe, venda ou conserte. Antes, apague seus dados e tire o chip e o cartão de memória.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "carregador", nome: "Carregador e fone de ouvido", palavras: ["carregador", "fone", "fone de ouvido", "headset", "fonte de celular"],
      resposta: "Carregador e fone são eletroeletrônicos.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita esses itens. " + REVERSA,
      lixeira: null, dicaReducao: "Carregadores com o mesmo encaixe servem em vários aparelhos: reaproveite antes de comprar outro.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "cabo", nome: "Fio e cabo", palavras: ["fio", "cabo", "cabo usb", "fio eletrico", "extensao", "cabo de rede"],
      resposta: "Fios e cabos têm cobre e plástico; não vão no lixo comum.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita fios e cabos. Se for de aparelho eletrônico: " + REVERSA,
      lixeira: null, dicaReducao: "Guarde cabos que ainda funcionam numa caixa: eles costumam servir em outros aparelhos.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "computador", nome: "Computador e notebook", palavras: ["computador", "notebook", "laptop", "pc", "monitor", "teclado", "mouse", "impressora"],
      resposta: "Computador, monitor e periféricos são lixo eletrônico.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita computadores. " + REVERSA,
      lixeira: null, dicaReducao: "Apague seus arquivos antes. Peças que funcionam (memória, teclado, monitor) podem ser doadas.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "tv", nome: "Televisão", palavras: ["tv", "televisao", "televisor", "smart tv"],
      resposta: "Televisão é eletroeletrônico.",
      ondeDescartar: "A matéria diz que os Ecopontos recebem eletrodomésticos, mas não diz se televisão entra. " + REVERSA,
      lixeira: null, dicaReducao: "Se ainda funciona, doe. TV quebrada às vezes tem conserto barato.",
      confianca: CONFIRME, tipoPonto: "pev" },
    { id: "pilha", nome: "Pilha", palavras: ["pilha", "pilhas", "pilha alcalina", "bateria pequena", "pilha de controle"],
      resposta: "Os Ecopontos NÃO recebem pilhas (a matéria da Agência Mural diz isso).",
      ondeDescartar: "Pilha nunca vai no lixo comum. " + REVERSA,
      lixeira: "laranja", dicaReducao: "Prefira pilhas recarregáveis: uma substitui muitas descartáveis.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "bateria", nome: "Bateria de celular ou notebook", palavras: ["bateria", "bateria de celular", "bateria de notebook", "bateria viciada", "bateria inchada"],
      resposta: "Os Ecopontos NÃO recebem baterias (a matéria da Agência Mural diz isso).",
      ondeDescartar: "Bateria nunca vai no lixo comum. Se estiver inchada, não fure nem amasse. " + REVERSA,
      lixeira: "laranja", dicaReducao: "Evite deixar o celular sempre em 100% e no calor: a bateria dura mais.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "lampada", nome: "Lâmpada fluorescente", palavras: ["lampada", "lampada fluorescente", "lampada fria", "lampada de mercurio", "lampada tubular"],
      resposta: "Os Ecopontos NÃO recebem lâmpadas fluorescentes (a matéria da Agência Mural diz isso).",
      ondeDescartar: "Ela tem mercúrio: embrulhe para não quebrar. " + REVERSA,
      lixeira: "laranja", dicaReducao: "Ao trocar, prefira lâmpada LED: gasta menos energia e dura mais.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "lampada-led", nome: "Lâmpada LED", palavras: ["lampada led", "led", "lampada de led"],
      resposta: "Lâmpada LED tem componentes eletrônicos.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita lâmpada LED. Pergunte nas lojas que vendem e confirme com a Prefeitura de Guarulhos.",
      lixeira: null, dicaReducao: "Apague a luz ao sair do cômodo: a lâmpada dura mais.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "eletrodomestico", nome: "Eletrodoméstico", palavras: ["eletrodomestico", "geladeira", "fogao", "micro ondas", "microondas", "maquina de lavar", "liquidificador", "ventilador", "ferro de passar", "batedeira", "freezer"],
      resposta: "Eletrodoméstico pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: null, dicaReducao: "Antes de descartar, veja se tem conserto ou se alguém aceita como doação.",
      confianca: CONFIRMADO, tipoPonto: "pev" },

    /* ---------- Roupas e objetos ---------- */
    { id: "roupa", nome: "Roupa em bom estado", palavras: ["roupa", "roupas", "camiseta", "camisa", "calca", "blusa", "casaco", "vestido", "uniforme", "bermuda", "saia", "jaqueta"],
      resposta: "Roupa boa não é lixo: doe ou troque.",
      ondeDescartar: "Os Ecopontos não são lugar de doação e a matéria não cita roupa. Leve a um ponto de doação (bazar, ONG, igreja), mas confirme antes. Ainda não temos pontos de doação confirmados.",
      lixeira: null, dicaReducao: "Lave antes de doar. Trocar roupa com amigos também evita comprar nova.",
      confianca: CONFIRME, tipoPonto: "doacao" },
    { id: "roupa-rasgada", nome: "Roupa rasgada ou manchada", palavras: ["roupa rasgada", "roupa manchada", "roupa velha", "retalho", "tecido", "pano velho", "trapo"],
      resposta: "Tecido estragado ainda pode ter uso.",
      ondeDescartar: "Não temos regra confirmada para tecido estragado em Guarulhos. Alguns pontos de doação aceitam para reciclagem têxtil: confirme antes. Confirme com a Prefeitura de Guarulhos.",
      lixeira: null, dicaReducao: "Vire pano de limpeza em casa ou conserte: um ponto de costura resolve muita coisa.",
      confianca: CONFIRME, tipoPonto: "doacao" },
    { id: "calcado", nome: "Calçado", palavras: ["calcado", "sapato", "tenis", "chinelo", "sandalia", "bota"],
      resposta: "Calçado em bom estado pode ser doado.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita calçados. Leve a um ponto de doação e confirme antes de ir.",
      lixeira: null, dicaReducao: "Amarre os pares juntos para não se perderem. Sola descolada tem conserto.",
      confianca: CONFIRME, tipoPonto: "doacao" },
    { id: "cobertor", nome: "Cobertor, lençol e toalha", palavras: ["cobertor", "coberta", "edredom", "lencol", "toalha", "manta"],
      resposta: "Cobertor e roupa de cama limpos são muito procurados em doação, principalmente no frio.",
      ondeDescartar: "Leve a um ponto de doação (ONG, igreja, campanha do agasalho) e confirme antes de ir.",
      lixeira: null, dicaReducao: "Toalha velha vira pano de chão.",
      confianca: CONFIRME, tipoPonto: "doacao" },
    { id: "brinquedo", nome: "Brinquedo", palavras: ["brinquedo", "boneca", "carrinho", "jogo", "pelucia", "lego", "bola"],
      resposta: "Brinquedo inteiro pode ser doado.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita brinquedos. Leve a um ponto de doação e confirme antes de ir. Se tiver pilha, tire antes.",
      lixeira: null, dicaReducao: "Confira se não faltam peças. Trocar brinquedos entre amigos e primos também vale.",
      confianca: CONFIRME, tipoPonto: "doacao" },
    { id: "livro", nome: "Livro", palavras: ["livro", "livros", "gibi", "livro didatico", "apostila"],
      resposta: "Livro em bom estado é ótimo para doar.",
      ondeDescartar: "Bibliotecas, escolas e sebos às vezes aceitam: confirme antes de ir. Se estiver estragado, vai como papel (veja \"papel\").",
      lixeira: null, dicaReducao: "Passe livros didáticos para alunos do ano seguinte.",
      confianca: CONFIRME, tipoPonto: "doacao" },
    { id: "movel", nome: "Móvel e colchão", palavras: ["movel", "moveis", "sofa", "colchao", "cadeira", "mesa", "armario", "estante", "cama", "guarda roupa"],
      resposta: "Móveis, sofás e colchões podem ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: null, dicaReducao: "Se ainda está bom, doe. Muitos móveis só precisam de um parafuso ou de uma lixa.",
      confianca: CONFIRMADO, tipoPonto: "pev" },

    /* ---------- Cozinha ---------- */
    { id: "oleo", nome: "Óleo de cozinha usado", palavras: ["oleo", "oleo de cozinha", "oleo usado", "oleo de fritura", "gordura de fritura"],
      resposta: "Óleo de cozinha pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM + " Espere esfriar e guarde numa garrafa PET bem fechada.",
      lixeira: null, dicaReducao: "Nunca jogue na pia nem no ralo: entope o encanamento e polui a água.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "vidro", nome: "Vidro de embalagem", palavras: ["vidro", "garrafa de vidro", "pote de vidro", "vidro de conserva", "copo de vidro", "frasco de vidro"],
      resposta: "Vidro é reciclável e pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM + " Se estiver quebrado, embrulhe em jornal para proteger quem coleta.",
      lixeira: "verde", dicaReducao: "Potes de vidro limpos servem para guardar comida e grãos.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "espelho", nome: "Espelho e vidro de janela", palavras: ["espelho", "vidro de janela", "vidro temperado", "box de banheiro", "vidro plano"],
      resposta: "Espelho e vidro de janela são diferentes do vidro de embalagem.",
      ondeDescartar: "A matéria diz que os Ecopontos recebem vidro, mas não diz se espelho e vidro plano entram. Confirme com a Prefeitura de Guarulhos. Embrulhe bem para ninguém se cortar.",
      lixeira: null, dicaReducao: "Espelho inteiro pode ser doado.",
      confianca: CONFIRME, tipoPonto: "pev" },
    { id: "papelao", nome: "Papelão", palavras: ["papelao", "caixa de papelao", "caixa", "caixa de sapato", "embalagem de papelao"],
      resposta: "Papelão é reciclável e pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM + " Desmonte e dobre as caixas.",
      lixeira: "azul", dicaReducao: "Caixas firmes servem para guardar coisas ou para mudanças.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "papel", nome: "Papel", palavras: ["papel", "folha", "folha de papel", "jornal", "revista", "caderno", "papel de escritorio", "envelope"],
      resposta: "Papel limpo e seco é reciclável e pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: "azul", dicaReducao: "Use os dois lados da folha antes de descartar.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "papel-sujo", nome: "Papel engordurado ou usado no banheiro", palavras: ["papel engordurado", "guardanapo", "guardanapo usado", "papel toalha", "papel higienico", "lenco de papel"],
      resposta: "Papel sujo de gordura ou usado no banheiro não entra junto com o papel limpo.",
      ondeDescartar: "Não temos regra confirmada para Guarulhos; em geral vai na coleta comum. A matéria diz que os Ecopontos não recebem lixo de banheiro. Confirme com a Prefeitura de Guarulhos.",
      lixeira: "cinza", dicaReducao: "Pano de prato lavável substitui muito papel toalha.",
      confianca: CONFIRME, tipoPonto: "nenhum" },
    { id: "pizza", nome: "Caixa de pizza", palavras: ["caixa de pizza", "pizza", "caixa de pizza suja"],
      resposta: "A parte limpa da caixa de pizza é papelão; a parte com gordura não é.",
      ondeDescartar: "Rasgue e separe: a parte limpa vai como papelão. A parte engordurada não tem regra confirmada para Guarulhos: confirme com a Prefeitura de Guarulhos.",
      lixeira: null, dicaReducao: "Separar as partes leva 10 segundos e salva o papelão limpo.",
      confianca: CONFIRME, tipoPonto: "nenhum" },
    { id: "plastico", nome: "Plástico", palavras: ["plastico", "embalagem plastica", "sacola", "sacolinha", "pote de plastico", "pote plastico", "embalagem de shampoo", "tampinha"],
      resposta: "Plástico limpo é reciclável e pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM + " Tire os restos de comida antes.",
      lixeira: "vermelho", dicaReducao: "Leve sacola retornável e garrafa própria: menos plástico para descartar.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "pet", nome: "Garrafa PET", palavras: ["pet", "garrafa pet", "garrafa plastica", "garrafa de refrigerante", "garrafa de agua"],
      resposta: "Garrafa PET é plástico reciclável e pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM + " Esvazie e amasse para ocupar menos espaço.",
      lixeira: "vermelho", dicaReducao: "Use garrafa reutilizável no dia a dia.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "isopor", nome: "Isopor", palavras: ["isopor", "bandeja de isopor", "copo de isopor", "caixa de isopor"],
      resposta: "Isopor é um tipo de plástico, mas nem todo lugar aceita.",
      ondeDescartar: "A matéria diz que os Ecopontos recebem plástico, mas não cita isopor. Confirme com a Prefeitura de Guarulhos.",
      lixeira: "vermelho", dicaReducao: "Caixa de isopor inteira serve para guardar coisas ou levar gelo.",
      confianca: CONFIRME, tipoPonto: "pev" },
    { id: "lata", nome: "Lata", palavras: ["lata", "latinha", "lata de refrigerante", "lata de conserva", "lata de leite em po"],
      resposta: "Lata é metal reciclável e pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM + " Pode amassar.",
      lixeira: "amarelo", dicaReducao: "Lata de conserva limpa vira vaso ou porta-lápis.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "aluminio", nome: "Alumínio", palavras: ["aluminio", "papel aluminio", "marmitex", "marmita de aluminio", "forma de aluminio"],
      resposta: "Alumínio é metal e pode ir para o Ecoponto, se estiver limpo.",
      ondeDescartar: PEV_SIM + " Tire os restos de comida.",
      lixeira: "amarelo", dicaReducao: "Prefira pote reutilizável para levar comida.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "metal", nome: "Metal e ferro", palavras: ["metal", "ferro", "ferro velho", "panela", "panela velha", "prego", "parafuso", "sucata"],
      resposta: "Metal é reciclável e pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: "amarelo", dicaReducao: "Panela boa sem cabo às vezes só precisa de um cabo novo.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "longa-vida", nome: "Embalagem longa vida", palavras: ["longa vida", "caixa de leite", "caixa de suco", "tetra pak", "tetrapak", "embalagem longa vida"],
      resposta: "Caixa de leite e de suco é feita de papel, plástico e alumínio juntos.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita embalagem longa vida. Confirme com a Prefeitura de Guarulhos. Enxágue e dobre antes.",
      lixeira: null, dicaReducao: "Prefira embalagens maiores ou refil: menos caixas por litro.",
      confianca: CONFIRME, tipoPonto: "pev" },
    { id: "esponja", nome: "Esponja de cozinha", palavras: ["esponja", "esponja de cozinha", "esponja de lavar louca", "bucha"],
      resposta: "Esponja de cozinha usada não tem regra confirmada.",
      ondeDescartar: "Não temos regra confirmada para Guarulhos; em geral vai na coleta comum. Confirme com a Prefeitura de Guarulhos.",
      lixeira: "cinza", dicaReducao: "Bucha vegetal é uma alternativa que se decompõe.",
      confianca: CONFIRME, tipoPonto: "nenhum" },

    /* ---------- Alimentos ---------- */
    { id: "resto-comida", nome: "Resto de comida e cascas", palavras: ["resto de comida", "restos de comida", "comida estragada", "casca", "cascas", "casca de fruta", "borra de cafe", "sobra do prato", "organico"],
      resposta: "Os Ecopontos NÃO recebem restos de comida (a matéria da Agência Mural diz isso).",
      ondeDescartar: "Não leve ao Ecoponto. Cascas e borra de café podem virar adubo numa composteira. O resto, em geral, vai na coleta comum. Confirme com a Prefeitura de Guarulhos.",
      lixeira: "marrom", dicaReducao: "Planeje as compras e guarde sobras na geladeira: menos comida no lixo.",
      confianca: CONFIRME, tipoPonto: "nenhum" },
    { id: "alimento-bom", nome: "Comida boa para doar", palavras: ["comida", "alimento", "alimentos", "doar comida", "cesta basica", "comida que sobrou", "alimento nao perecivel", "marmita"],
      resposta: "Comida boa não é lixo: pode ser doada.",
      ondeDescartar: "Os Ecopontos não recebem comida. Bancos de alimentos, ONGs e igrejas recebem doações, mas ainda não temos locais confirmados: confirme antes de ir. A plataforma Ciclo Prato do Ciclo 12 vai ligar doadores e receptores.",
      lixeira: null, dicaReducao: "Confira a validade antes de doar e leve alimentos fechados.",
      confianca: CONFIRME, tipoPonto: "doacao" },

    /* ---------- Casa, obra e outros ---------- */
    { id: "remedio", nome: "Remédio vencido", palavras: ["remedio", "remedio vencido", "medicamento", "medicamento vencido", "comprimido", "xarope", "cartela de remedio"],
      resposta: "Remédio vencido não vai no lixo comum nem na pia.",
      ondeDescartar: "Muitas farmácias têm coletor de remédios vencidos, mas não confirmamos quais em Guarulhos. Confirme com a Prefeitura de Guarulhos ou pergunte na farmácia.",
      lixeira: null, dicaReducao: "Compre só a quantidade receitada e guarde a caixa com a bula.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "tinta", nome: "Tinta e solvente", palavras: ["tinta", "lata de tinta", "solvente", "thinner", "verniz", "tiner"],
      resposta: "Tinta e solvente são resíduos perigosos.",
      ondeDescartar: "A matéria sobre os Ecopontos não cita tinta. Não jogue no ralo. Confirme com a Prefeitura de Guarulhos.",
      lixeira: "laranja", dicaReducao: "Calcule a quantidade antes de comprar. Sobra de tinta boa pode ser doada.",
      confianca: CONFIRME, tipoPonto: "nenhum" },
    { id: "oleo-motor", nome: "Óleo de motor", palavras: ["oleo de motor", "oleo lubrificante", "oleo de carro", "oleo queimado"],
      resposta: "Os Ecopontos NÃO recebem óleo lubrificante (a matéria da Agência Mural diz isso).",
      ondeDescartar: REVERSA,
      lixeira: "laranja", dicaReducao: "Troque o óleo em oficinas que recolhem o óleo usado.",
      confianca: CONFIRME, tipoPonto: "varejo" },
    { id: "entulho", nome: "Entulho", palavras: ["entulho", "tijolo", "cimento", "concreto", "azulejo", "piso", "material de construcao", "reboco"],
      resposta: "Entulho e materiais de construção podem ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: null, dicaReducao: "Sobra de piso e tijolo inteiro pode ser doada para outra obra.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "gesso", nome: "Gesso", palavras: ["gesso", "placa de gesso", "drywall", "forro de gesso"],
      resposta: "Gesso pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM + " Leve separado do resto do entulho.",
      lixeira: null, dicaReducao: "Compre a quantidade certa para a obra.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "terra", nome: "Terra", palavras: ["terra", "solo", "areia", "barro"],
      resposta: "Terra (solo) pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: null, dicaReducao: "Terra boa pode ser usada em vasos e hortas.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "poda", nome: "Folhas e restos de poda", palavras: ["poda", "folhas", "galho", "galhos", "grama", "capim", "tronco", "restos de poda", "capina"],
      resposta: "Folhas, galhos e restos de poda podem ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: null, dicaReducao: "Folhas secas viram adubo numa composteira.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "madeira", nome: "Madeira", palavras: ["madeira", "tabua", "porta", "janela de madeira", "pallet", "palete", "esquadria", "caixote"],
      resposta: "Madeira e esquadrias podem ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: "preto", dicaReducao: "Madeira boa vira prateleira, horta ou móvel.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "pneu", nome: "Pneu", palavras: ["pneu", "pneus", "pneu velho", "pneu de bicicleta", "camara de ar"],
      resposta: "Pneu pode ir para o Ecoponto.",
      ondeDescartar: PEV_SIM + " Nunca deixe pneu no quintal: acumula água e cria mosquito da dengue.",
      lixeira: null, dicaReducao: "Calibrar os pneus faz eles durarem mais.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "vaso-sanitario", nome: "Vaso sanitário e pia de louça", palavras: ["vaso sanitario", "privada", "pia", "pia de louca", "sanitario", "louca sanitaria", "tanque"],
      resposta: "Sanitários de cerâmica podem ir para o Ecoponto.",
      ondeDescartar: PEV_SIM,
      lixeira: null, dicaReducao: "Peça inteira e sem trinca pode ser doada para outra obra.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "ceramica", nome: "Cerâmica e louça quebrada", palavras: ["ceramica", "prato quebrado", "louca quebrada", "caneca quebrada", "porcelana", "xicara quebrada"],
      resposta: "Prato e caneca de cerâmica não vão junto com o vidro.",
      ondeDescartar: "A matéria cita sanitários de cerâmica e entulho, mas não louça de cozinha. Confirme com a Prefeitura de Guarulhos. Embrulhe os cacos.",
      lixeira: null, dicaReducao: "Caneca lascada vira vaso de planta.",
      confianca: CONFIRME, tipoPonto: "pev" },
    { id: "telha", nome: "Telha e caixa d'água", palavras: ["telha", "caixa d agua", "caixa dagua", "telha de fibrocimento", "amianto", "telha de amianto"],
      resposta: "Telha e caixa d'água de fibrocimento SEM amianto podem ir para o Ecoponto. COM amianto, não.",
      ondeDescartar: PEV_SIM + " A matéria diz que os Ecopontos não recebem telhas e caixas d'água com amianto: para essas, confirme com a Prefeitura de Guarulhos.",
      lixeira: null, dicaReducao: "Amianto faz mal à saúde: não quebre nem lixe a peça.",
      confianca: CONFIRMADO, tipoPonto: "pev" },
    { id: "fralda", nome: "Fralda e absorvente", palavras: ["fralda", "fralda descartavel", "absorvente", "lixo de banheiro", "cotonete"],
      resposta: "Os Ecopontos NÃO recebem lixo de banheiro (a matéria da Agência Mural diz isso).",
      ondeDescartar: "Não leve ao Ecoponto. Em geral vai na coleta comum, bem fechado. Confirme com a Prefeitura de Guarulhos.",
      lixeira: "cinza", dicaReducao: "Fralda de pano e coletor menstrual são opções reutilizáveis.",
      confianca: CONFIRME, tipoPonto: "nenhum" }
  ];

  /* Perguntas que não são sobre um item */
  var INTENCOES = [
    { id: "saudacao", palavras: ["oi", "ola", "bom dia", "boa tarde", "boa noite", "eai", "e ai", "hey", "salve"] },
    { id: "agradecimento", palavras: ["obrigado", "obrigada", "valeu", "vlw", "brigado", "agradeco"] },
    { id: "ajuda", palavras: ["ajuda", "menu", "inicio", "comecar", "o que voce faz", "opcoes"] },
    { id: "ods", palavras: ["ods", "ods 12", "ods12", "objetivo", "consumo responsavel", "onu", "agenda 2030"] },
    { id: "cores", palavras: ["cor", "cores", "lixeira", "lixeiras", "cor da lixeira", "cores da lixeira", "coleta seletiva", "conama"] },
    { id: "perto", palavras: ["ponto mais perto", "mais perto", "perto", "ecoponto", "ecopontos", "pev", "pevs", "onde fica", "endereco", "proximo"] }
  ];

  var dados = { ITENS: ITENS, INTENCOES: INTENCOES, LIXEIRAS: LIXEIRAS, CONFIRMADO: CONFIRMADO, CONFIRME: CONFIRME };
  if (typeof module !== "undefined" && module.exports) { module.exports = dados; }
  if (raiz) { raiz.CICLO_BOT = dados; }
})(typeof window !== "undefined" ? window : null);
